name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\\, [*_`]'  # Escape markdown special characters
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

  **Full Changelog**: $PREVIOUS_TAG...$RESOLVED_VERSION
