repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=100]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280
    hooks:
    -   id: ruff
        args: [--fix, --show-fixes]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-requests, types-python-dateutil]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
    -   id: prettier
        types_or: [markdown, yaml, json, html, css, scss, javascript, typescript, tsx, jsx]
        args: [--write, --print-width=100, --prose-wrap=always]
